---
title: "Chapter 2"
author: "Nikos Giannakis"
date: "28/2/2022"
output: pdf_document
---

library(ISLR2)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r }
x <- c(1,3,2,5)
print(length(x))
y = c(1,4,3)
print(ls())
rm(x,y)
print(ls())
```

## Including Plots

You can also embed plots, for example:

```{r }
x <- matrix(data=c(1,2,3,4), nrow=2, ncol=2)
print(x)
x <- matrix(c(1,2,3,4),2,2, byrow=T)
print(x)
print(sqrt(x))
```

## Descriptive

```{r }
x <- rnorm(50)
y <- x+ rnorm(50, mean=50, sd=0.1)
print(cor(x,y))
set.seed(3)
y <- rnorm(100)
print(mean(y))
print(var(y))
print(median(y))
print(sqrt(var(y)))
print(sd(y))
```

##plots

```{r}
x <- rnorm(100)
y <- rnorm(100)
plot(x,y)
plot(x,y,xlab="X-Axis", ylab="Y-axis", main="Plot X-Y")

#pdf("Figure.pdf")
plot(x,y,col="green")
#dev.off()


```


``` {r}
x <- seq(1,10)
print(x)
x<- 1:10
print(x)
```

``` {r}
x<-seq(-pi, pi, lengt=50)
y<-x
f <- outer(x,y, function(x,y) cos(y) / (1+x^2))
contour(x,y,f)
contour(x,y,f,nlevels = 45, add = T)
fa<- (f - t(f))/2
contour(x, y, fa, nlevels = 15)

```

``` {r}
image(x,y,fa)
persp(x,y,fa)
persp(x, y, fa , theta = 30)
persp(x, y, fa , theta = 30, phi = 20)
persp(x, y, fa , theta = 30, phi = 70)
persp(x, y, fa , theta = 30, phi = 40)
```


## indexing

``` {r}
A<- matrix(1:16, 4, 4)
print(A)
print(A[2,3])
print(A[c(1,3), c(2,4)])
print(A[1,])
print(A[-c(1,3),])
print(dim(A))
```

## Loading data

```{r}
library(ISLR2)
Auto <-Auto
View(Auto)
head(Auto)
dim(Auto)
# Auto <- read.table("Auto.data", header = T, na.strings = "?", stringsAsFactors = T)
# Auto <- read.csv("Auto.csv", na.strings = "?", stringsAsFactors = T)

Auto <- na.omit(Auto)
dim(Auto)
names(Auto)

```

## Additional Graphical and Numerical Summaries

### Boxplot and *attach*
```{r}
plot(Auto$cylinders , Auto$mpg)
attach(Auto)
#we can use the attach() function in order to tell R to make the variables in this data frame available by name
plot(cylinders , mpg)

#The as.factor() function converts quantitative variables into qualitative variables
cyliders <-as.factor(cylinders)

plot(cylinders , mpg)
plot(cylinders , mpg , col = "red")
plot(cylinders , mpg , col = "red", varwidth = T)
plot(cylinders , mpg , col = "red", varwidth = T,horizontal = T)
plot(cylinders , mpg , col = "red", varwidth = T,xlab = "cylinders", ylab = "MPG")
```
### Hist
```{r}
hist(mpg)
hist(mpg , col = 2)
hist(mpg , col = 2, breaks = 15)
```
### Scatterplot   **identify**
```{r}
pairs(Auto)
pairs( ~mpg + displacement + horsepower + weight + acceleration , data = Auto)

#to identify(): the x-axis variable, the y-axis variable, and the variable whose values we would #like to see printed for each point.

plot(horsepower, mpg)
#identify(horsepower, mpg, name)
```
```{r}
summary(Auto)
summary(mpg)
```
```{r, echo=F}
print(" if you type g() then you shut down R")
print("we can save through savehistory() and the load through loadhistory()")
```